import "dotenv/config";

import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { sql } from "drizzle-orm";
import * as schema from "./schema";
import { v4 as uuidv4 } from "uuid";
import { faker } from "@faker-js/faker";
import "dotenv/config";

if (!process.env.DATABASE_URL) {
  throw new Error("❌ DATABASE_URL is not set. Check your .env file!");
}

// Initialize DB
const neonClient = neon(process.env.DATABASE_URL!);
const db = drizzle(neonClient, { schema });

// CONFIGURATION
const NUM_PRODUCTS = 1000; // Stress test volume
const NUM_ORGS = 5;
const NUM_USERS_PER_ORG = 4;

async function seed() {
  console.log("🔥 Starting HEAVY Stress Test Seed...");
  const start = performance.now();

  // 1. CLEANUP (Truncate all tables to ensure clean slate)
  // We use CASCADE to wipe child tables automatically
  console.log("... Wiping existing data");
  await db.execute(sql`
    TRUNCATE TABLE 
      "order_item", 
      "order", 
      "cart_item", 
      "cart", 
      "inventory", 
      "pricing_tier", 
      "product", 
      "member", 
      "organization_address", 
      "audit_log", 
      "organization", 
      "sessions", 
      "accounts", 
      "verifications", 
      "users", 
      "warehouse"
    CASCADE;
  `);

  // WAREHOUSES
  console.log("... Seeding Logistics (Warehouses)");
  const warehouseIds = [uuidv4(), uuidv4()];
  await db.insert(schema.warehouses).values([
    {
      id: warehouseIds[0],
      name: "East Coast Distribution (NY)",
      address: {
        city: "New York",
        state: "NY",
        zip: "10001",
        lines: ["123 Harbor Blvd"],
      },
    },
    {
      id: warehouseIds[1],
      name: "West Coast Hub (LA)",
      address: {
        city: "Los Angeles",
        state: "CA",
        zip: "90001",
        lines: ["456 Sunset Ind. Park"],
      },
    },
  ]);

  // PRODUCTS
  console.log(`... Seeding ${NUM_PRODUCTS} Products (This may take a moment)`);

  // Prepare data arrays for batch insertion
  const productsData: (typeof schema.products.$inferInsert)[] = [];

  for (let i = 0; i < NUM_PRODUCTS; i++) {
    productsData.push({
      // ID is auto-generated by DB (Identity), we don't send it.
      name: faker.commerce.productName(),
      slug: faker.helpers
        .slugify(faker.commerce.productName() + "-" + faker.string.alpha(5))
        .toLowerCase(),
      description: faker.commerce.productDescription(),
      basePrice: faker.commerce.price({ min: 10, max: 2000 }), // Random string price
      unitOfMeasure: faker.helpers.arrayElement([
        "each",
        "box",
        "pallet",
        "roll",
        "meter",
      ]),
      minOrderQuantity: faker.helpers.arrayElement([1, 1, 1, 5, 10, 50]),
      isArchived: faker.datatype.boolean(0.05), // 5% chance of being archived
    });
  }

  // Batch Insert Products (Drizzle returns inserted rows so we can get IDs)
  // We do chunks of 100 to avoid packet size limits
  const insertedProducts = await db
    .insert(schema.products)
    .values(productsData)
    .returning({
      id: schema.products.id,
      basePrice: schema.products.basePrice,
    });

  // PRICING TIERS & INVENTORY (Linked to Products)
  console.log("... Seeding Pricing Tiers & Inventory Matrices");

  const pricingTiersData: (typeof schema.pricingTiers.$inferInsert)[] = [];
  const inventoryData: (typeof schema.inventory.$inferInsert)[] = [];

  for (const product of insertedProducts) {
    const base = parseFloat(product.basePrice);

    // TIER 1: Standard (1 unit)
    pricingTiersData.push({
      productId: product.id,
      minQuantity: 1,
      unitPrice: base.toFixed(2),
    });

    // TIER 2: Bulk (10+ units) -> 10% off
    pricingTiersData.push({
      productId: product.id,
      minQuantity: 10,
      unitPrice: (base * 0.9).toFixed(2),
    });

    // TIER 3: Wholesale (50+ units) -> 20% off
    pricingTiersData.push({
      productId: product.id,
      minQuantity: 50,
      unitPrice: (base * 0.8).toFixed(2),
    });

    // Inventory: Randomly distribute between warehouses
    // Scenario: Some items only in East, some in both, some OOS.
    inventoryData.push({
      productId: product.id,
      warehouseId: warehouseIds[0] || "",
      stockOnHand: faker.number.int({ min: 0, max: 500 }),
      reservedStock: faker.number.int({ min: 0, max: 20 }),
    });
    inventoryData.push({
      productId: product.id,
      warehouseId: warehouseIds[1] || "",
      stockOnHand: faker.number.int({ min: 0, max: 500 }),
      reservedStock: 0,
    });
  }

  // Batch insert aux tables
  // Chunking again for safety
  const chunkSize = 500;
  for (let i = 0; i < pricingTiersData.length; i += chunkSize) {
    await db
      .insert(schema.pricingTiers)
      .values(pricingTiersData.slice(i, i + chunkSize));
  }
  for (let i = 0; i < inventoryData.length; i += chunkSize) {
    await db
      .insert(schema.inventory)
      .values(inventoryData.slice(i, i + chunkSize));
  }

  // ORGANIZATIONS & USERS (The Multi-Tenancy Layer)
  console.log("... Seeding Organizations & Users");

  // Create your specific "Test Org" first
  const mainOrgId = uuidv4();
  const mainUserId = uuidv4();

  await db.insert(schema.organizations).values({
    id: mainOrgId,
    name: "Scala Industries (Demo)",
    slug: "scala-demo",
    creditLimit: "100000.00",
    usedCredit: "12500.50",
    taxIdentifier: "VAT-US-9999",
  });

  await db.insert(schema.users).values({
    id: mainUserId,
    name: "Prashant (Procurement)",
    email: "prashant@scala.com",
    activeOrganizationId: mainOrgId,
  });

  await db.insert(schema.members).values({
    organizationId: mainOrgId,
    userId: mainUserId,
    role: "buyer",
  });

  //   Create random background Orgs
  for (let i = 0; i < NUM_ORGS; i++) {
    const orgId = uuidv4();
    await db.insert(schema.organizations).values({
      id: orgId,
      name: faker.company.name(),
      slug: faker.helpers.slugify(faker.company.name() + i).toLowerCase(), // Unique slug
      creditLimit: faker.finance.amount({ min: 10000, max: 500000 }),
      usedCredit: faker.finance.amount({ min: 0, max: 5000 }),
      taxIdentifier: "EIN-" + faker.string.numeric(9),
    });

    // Add users to this org
    for (let j = 0; j < NUM_USERS_PER_ORG; j++) {
      const uId = uuidv4();
      await db.insert(schema.users).values({
        id: uId,
        name: faker.person.fullName(),
        email: faker.internet.email(),
        activeOrganizationId: orgId,
      });

      await db.insert(schema.members).values({
        organizationId: orgId,
        userId: uId,
        role: j === 0 ? "admin" : "buyer", // First user is admin
      });
    }
  }

  const end = performance.now();
  console.log(`✅ Seed Complete in ${((end - start) / 1000).toFixed(2)}s`);
  console.log(`   - ${insertedProducts.length} Products`);
  console.log(`   - ${pricingTiersData.length} Pricing Tiers`);
  console.log(`   - ${inventoryData.length} Inventory Records`);
  console.log(`   - Check 'Scala Industries' with user 'prashant@scala.com'`);
}

seed().catch((err) => {
  console.error("❌ Seed Failed:", err);
  process.exit(1);
});
